[package]
name = "workers-ts-plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
toml = "0.8.10"
wasm-bindgen = { version = "0.2.91", features = ["serde"] }

[lib]
crate-type = ["cdylib"]
